/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class FinGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Model");
		private final Assignment cElementAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementElementParserRuleCall_0 = (RuleCall)cElementAssignment.eContents().get(0);
		
		//Model:
		//    (element+=Element)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(element+=Element)*
		public Assignment getElementAssignment() { return cElementAssignment; }
		
		//Element
		public RuleCall getElementElementParserRuleCall_0() { return cElementElementParserRuleCall_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPortfolioParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTransactionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cActionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Element:
		//    Portfolio | Transaction | Action
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Portfolio | Transaction | Action
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Portfolio
		public RuleCall getPortfolioParserRuleCall_0() { return cPortfolioParserRuleCall_0; }
		
		//Transaction
		public RuleCall getTransactionParserRuleCall_1() { return cTransactionParserRuleCall_1; }
		
		//Action
		public RuleCall getActionParserRuleCall_2() { return cActionParserRuleCall_2; }
	}
	public class AssetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Asset");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBondParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOptionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCashParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Asset:
		//    Bond | Option | Cash
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Bond | Option | Cash
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Bond
		public RuleCall getBondParserRuleCall_0() { return cBondParserRuleCall_0; }
		
		//Option
		public RuleCall getOptionParserRuleCall_1() { return cOptionParserRuleCall_1; }
		
		//Cash
		public RuleCall getCashParserRuleCall_2() { return cCashParserRuleCall_2; }
	}
	public class TransactionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Transaction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBuyParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSellParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDepositParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cWithdrawalParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Transaction:
		//    Buy | Sell | Deposit | Withdrawal
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Buy | Sell | Deposit | Withdrawal
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Buy
		public RuleCall getBuyParserRuleCall_0() { return cBuyParserRuleCall_0; }
		
		//Sell
		public RuleCall getSellParserRuleCall_1() { return cSellParserRuleCall_1; }
		
		//Deposit
		public RuleCall getDepositParserRuleCall_2() { return cDepositParserRuleCall_2; }
		
		//Withdrawal
		public RuleCall getWithdrawalParserRuleCall_3() { return cWithdrawalParserRuleCall_3; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cViewParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDeleteParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Action:
		//    View | Delete
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//View | Delete
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//View
		public RuleCall getViewParserRuleCall_0() { return cViewParserRuleCall_0; }
		
		//Delete
		public RuleCall getDeleteParserRuleCall_1() { return cDeleteParserRuleCall_1; }
	}
	public class PortfolioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Portfolio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPortfolioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAssetAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAssetAssetParserRuleCall_3_0 = (RuleCall)cAssetAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Portfolio:
		//    'portfolio' name=ID '{'
		//        (asset+=Asset)+
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'portfolio' name=ID '{'
		//    (asset+=Asset)+
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_0() { return cPortfolioKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(asset+=Asset)+
		public Assignment getAssetAssignment_3() { return cAssetAssignment_3; }
		
		//Asset
		public RuleCall getAssetAssetParserRuleCall_3_0() { return cAssetAssetParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BondElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Bond");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBondKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFaceValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFaceValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFaceValueFLOATParserRuleCall_4_0 = (RuleCall)cFaceValueAssignment_4.eContents().get(0);
		private final Keyword cCouponRateKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCouponRateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCouponRateFLOATParserRuleCall_6_0 = (RuleCall)cCouponRateAssignment_6.eContents().get(0);
		private final Keyword cMaturityKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cMaturityAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cMaturityINTTerminalRuleCall_8_0 = (RuleCall)cMaturityAssignment_8.eContents().get(0);
		private final Keyword cYieldRateKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cYieldRateAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cYieldRateFLOATParserRuleCall_10_0 = (RuleCall)cYieldRateAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Bond:
		//    'bond' name=ID '{'
		//        'faceValue' faceValue=FLOAT
		//        'couponRate' couponRate=FLOAT
		//        'maturity' maturity=INT
		//        'yieldRate' yieldRate=FLOAT
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'bond' name=ID '{'
		//    'faceValue' faceValue=FLOAT
		//    'couponRate' couponRate=FLOAT
		//    'maturity' maturity=INT
		//    'yieldRate' yieldRate=FLOAT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'bond'
		public Keyword getBondKeyword_0() { return cBondKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'faceValue'
		public Keyword getFaceValueKeyword_3() { return cFaceValueKeyword_3; }
		
		//faceValue=FLOAT
		public Assignment getFaceValueAssignment_4() { return cFaceValueAssignment_4; }
		
		//FLOAT
		public RuleCall getFaceValueFLOATParserRuleCall_4_0() { return cFaceValueFLOATParserRuleCall_4_0; }
		
		//'couponRate'
		public Keyword getCouponRateKeyword_5() { return cCouponRateKeyword_5; }
		
		//couponRate=FLOAT
		public Assignment getCouponRateAssignment_6() { return cCouponRateAssignment_6; }
		
		//FLOAT
		public RuleCall getCouponRateFLOATParserRuleCall_6_0() { return cCouponRateFLOATParserRuleCall_6_0; }
		
		//'maturity'
		public Keyword getMaturityKeyword_7() { return cMaturityKeyword_7; }
		
		//maturity=INT
		public Assignment getMaturityAssignment_8() { return cMaturityAssignment_8; }
		
		//INT
		public RuleCall getMaturityINTTerminalRuleCall_8_0() { return cMaturityINTTerminalRuleCall_8_0; }
		
		//'yieldRate'
		public Keyword getYieldRateKeyword_9() { return cYieldRateKeyword_9; }
		
		//yieldRate=FLOAT
		public Assignment getYieldRateAssignment_10() { return cYieldRateAssignment_10; }
		
		//FLOAT
		public RuleCall getYieldRateFLOATParserRuleCall_10_0() { return cYieldRateFLOATParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Option");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeOptionTypeEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cUnderlyingPriceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUnderlyingPriceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUnderlyingPriceFLOATParserRuleCall_6_0 = (RuleCall)cUnderlyingPriceAssignment_6.eContents().get(0);
		private final Keyword cStrikePriceKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cStrikePriceAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cStrikePriceFLOATParserRuleCall_8_0 = (RuleCall)cStrikePriceAssignment_8.eContents().get(0);
		private final Keyword cTimeToExpirationKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cTimeToExpirationAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cTimeToExpirationFLOATParserRuleCall_10_0 = (RuleCall)cTimeToExpirationAssignment_10.eContents().get(0);
		private final Keyword cRiskFreeRateKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cRiskFreeRateAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cRiskFreeRateFLOATParserRuleCall_12_0 = (RuleCall)cRiskFreeRateAssignment_12.eContents().get(0);
		private final Keyword cVolatilityKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cVolatilityAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cVolatilityFLOATParserRuleCall_14_0 = (RuleCall)cVolatilityAssignment_14.eContents().get(0);
		private final Keyword cDividendYieldKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cDividendYieldAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cDividendYieldFLOATParserRuleCall_16_0 = (RuleCall)cDividendYieldAssignment_16.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//Option:
		//    'option' name=ID '{'
		//        'type' type=OptionType
		//        'underlyingPrice' underlyingPrice=FLOAT
		//        'strikePrice' strikePrice=FLOAT
		//        'timeToExpiration' timeToExpiration=FLOAT
		//        'riskFreeRate' riskFreeRate=FLOAT
		//        'volatility' volatility=FLOAT
		//        'dividendYield' dividendYield=FLOAT
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'option' name=ID '{'
		//    'type' type=OptionType
		//    'underlyingPrice' underlyingPrice=FLOAT
		//    'strikePrice' strikePrice=FLOAT
		//    'timeToExpiration' timeToExpiration=FLOAT
		//    'riskFreeRate' riskFreeRate=FLOAT
		//    'volatility' volatility=FLOAT
		//    'dividendYield' dividendYield=FLOAT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'option'
		public Keyword getOptionKeyword_0() { return cOptionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=OptionType
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//OptionType
		public RuleCall getTypeOptionTypeEnumRuleCall_4_0() { return cTypeOptionTypeEnumRuleCall_4_0; }
		
		//'underlyingPrice'
		public Keyword getUnderlyingPriceKeyword_5() { return cUnderlyingPriceKeyword_5; }
		
		//underlyingPrice=FLOAT
		public Assignment getUnderlyingPriceAssignment_6() { return cUnderlyingPriceAssignment_6; }
		
		//FLOAT
		public RuleCall getUnderlyingPriceFLOATParserRuleCall_6_0() { return cUnderlyingPriceFLOATParserRuleCall_6_0; }
		
		//'strikePrice'
		public Keyword getStrikePriceKeyword_7() { return cStrikePriceKeyword_7; }
		
		//strikePrice=FLOAT
		public Assignment getStrikePriceAssignment_8() { return cStrikePriceAssignment_8; }
		
		//FLOAT
		public RuleCall getStrikePriceFLOATParserRuleCall_8_0() { return cStrikePriceFLOATParserRuleCall_8_0; }
		
		//'timeToExpiration'
		public Keyword getTimeToExpirationKeyword_9() { return cTimeToExpirationKeyword_9; }
		
		//timeToExpiration=FLOAT
		public Assignment getTimeToExpirationAssignment_10() { return cTimeToExpirationAssignment_10; }
		
		//FLOAT
		public RuleCall getTimeToExpirationFLOATParserRuleCall_10_0() { return cTimeToExpirationFLOATParserRuleCall_10_0; }
		
		//'riskFreeRate'
		public Keyword getRiskFreeRateKeyword_11() { return cRiskFreeRateKeyword_11; }
		
		//riskFreeRate=FLOAT
		public Assignment getRiskFreeRateAssignment_12() { return cRiskFreeRateAssignment_12; }
		
		//FLOAT
		public RuleCall getRiskFreeRateFLOATParserRuleCall_12_0() { return cRiskFreeRateFLOATParserRuleCall_12_0; }
		
		//'volatility'
		public Keyword getVolatilityKeyword_13() { return cVolatilityKeyword_13; }
		
		//volatility=FLOAT
		public Assignment getVolatilityAssignment_14() { return cVolatilityAssignment_14; }
		
		//FLOAT
		public RuleCall getVolatilityFLOATParserRuleCall_14_0() { return cVolatilityFLOATParserRuleCall_14_0; }
		
		//'dividendYield'
		public Keyword getDividendYieldKeyword_15() { return cDividendYieldKeyword_15; }
		
		//dividendYield=FLOAT
		public Assignment getDividendYieldAssignment_16() { return cDividendYieldAssignment_16; }
		
		//FLOAT
		public RuleCall getDividendYieldFLOATParserRuleCall_16_0() { return cDividendYieldFLOATParserRuleCall_16_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class CashElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Cash");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCashKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAmountKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAmountAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAmountFLOATParserRuleCall_3_0 = (RuleCall)cAmountAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Cash:
		//    'cash' '{'
		//        'amount' amount=FLOAT
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'cash' '{'
		//    'amount' amount=FLOAT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'cash'
		public Keyword getCashKeyword_0() { return cCashKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'amount'
		public Keyword getAmountKeyword_2() { return cAmountKeyword_2; }
		
		//amount=FLOAT
		public Assignment getAmountAssignment_3() { return cAmountAssignment_3; }
		
		//FLOAT
		public RuleCall getAmountFLOATParserRuleCall_3_0() { return cAmountFLOATParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BuyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Buy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPortfolioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortfolioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPortfolioPortfolioCrossReference_3_0 = (CrossReference)cPortfolioAssignment_3.eContents().get(0);
		private final RuleCall cPortfolioPortfolioIDTerminalRuleCall_3_0_1 = (RuleCall)cPortfolioPortfolioCrossReference_3_0.eContents().get(1);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Assignment cBondAssignment_4_0 = (Assignment)cAlternatives_4.eContents().get(0);
		private final RuleCall cBondBondParserRuleCall_4_0_0 = (RuleCall)cBondAssignment_4_0.eContents().get(0);
		private final Assignment cOptionAssignment_4_1 = (Assignment)cAlternatives_4.eContents().get(1);
		private final RuleCall cOptionOptionParserRuleCall_4_1_0 = (RuleCall)cOptionAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Buy:
		//    'buy' '{'
		//        'portfolio' portfolio=[Portfolio]
		//        (bond+=Bond | option+=Option)+
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'buy' '{'
		//    'portfolio' portfolio=[Portfolio]
		//    (bond+=Bond | option+=Option)+
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'buy'
		public Keyword getBuyKeyword_0() { return cBuyKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_2() { return cPortfolioKeyword_2; }
		
		//portfolio=[Portfolio]
		public Assignment getPortfolioAssignment_3() { return cPortfolioAssignment_3; }
		
		//[Portfolio]
		public CrossReference getPortfolioPortfolioCrossReference_3_0() { return cPortfolioPortfolioCrossReference_3_0; }
		
		//ID
		public RuleCall getPortfolioPortfolioIDTerminalRuleCall_3_0_1() { return cPortfolioPortfolioIDTerminalRuleCall_3_0_1; }
		
		//(bond+=Bond | option+=Option)+
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//bond+=Bond
		public Assignment getBondAssignment_4_0() { return cBondAssignment_4_0; }
		
		//Bond
		public RuleCall getBondBondParserRuleCall_4_0_0() { return cBondBondParserRuleCall_4_0_0; }
		
		//option+=Option
		public Assignment getOptionAssignment_4_1() { return cOptionAssignment_4_1; }
		
		//Option
		public RuleCall getOptionOptionParserRuleCall_4_1_0() { return cOptionOptionParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class SellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Sell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSellKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPortfolioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortfolioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPortfolioPortfolioCrossReference_3_0 = (CrossReference)cPortfolioAssignment_3.eContents().get(0);
		private final RuleCall cPortfolioPortfolioIDTerminalRuleCall_3_0_1 = (RuleCall)cPortfolioPortfolioCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBondKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBondAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cBondBondCrossReference_4_1_0 = (CrossReference)cBondAssignment_4_1.eContents().get(0);
		private final RuleCall cBondBondIDTerminalRuleCall_4_1_0_1 = (RuleCall)cBondBondCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cOptionOptionCrossReference_5_1_0 = (CrossReference)cOptionAssignment_5_1.eContents().get(0);
		private final RuleCall cOptionOptionIDTerminalRuleCall_5_1_0_1 = (RuleCall)cOptionOptionCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Sell:
		//    'sell' '{'
		//        'portfolio' portfolio=[Portfolio]
		//        ('bond' bond=[Bond])*
		//        ('option' option=[Option])*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'sell' '{'
		//    'portfolio' portfolio=[Portfolio]
		//    ('bond' bond=[Bond])*
		//    ('option' option=[Option])*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'sell'
		public Keyword getSellKeyword_0() { return cSellKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_2() { return cPortfolioKeyword_2; }
		
		//portfolio=[Portfolio]
		public Assignment getPortfolioAssignment_3() { return cPortfolioAssignment_3; }
		
		//[Portfolio]
		public CrossReference getPortfolioPortfolioCrossReference_3_0() { return cPortfolioPortfolioCrossReference_3_0; }
		
		//ID
		public RuleCall getPortfolioPortfolioIDTerminalRuleCall_3_0_1() { return cPortfolioPortfolioIDTerminalRuleCall_3_0_1; }
		
		//('bond' bond=[Bond])*
		public Group getGroup_4() { return cGroup_4; }
		
		//'bond'
		public Keyword getBondKeyword_4_0() { return cBondKeyword_4_0; }
		
		//bond=[Bond]
		public Assignment getBondAssignment_4_1() { return cBondAssignment_4_1; }
		
		//[Bond]
		public CrossReference getBondBondCrossReference_4_1_0() { return cBondBondCrossReference_4_1_0; }
		
		//ID
		public RuleCall getBondBondIDTerminalRuleCall_4_1_0_1() { return cBondBondIDTerminalRuleCall_4_1_0_1; }
		
		//('option' option=[Option])*
		public Group getGroup_5() { return cGroup_5; }
		
		//'option'
		public Keyword getOptionKeyword_5_0() { return cOptionKeyword_5_0; }
		
		//option=[Option]
		public Assignment getOptionAssignment_5_1() { return cOptionAssignment_5_1; }
		
		//[Option]
		public CrossReference getOptionOptionCrossReference_5_1_0() { return cOptionOptionCrossReference_5_1_0; }
		
		//ID
		public RuleCall getOptionOptionIDTerminalRuleCall_5_1_0_1() { return cOptionOptionIDTerminalRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class DepositElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Deposit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDepositKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPortfolioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortfolioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPortfolioPortfolioCrossReference_3_0 = (CrossReference)cPortfolioAssignment_3.eContents().get(0);
		private final RuleCall cPortfolioPortfolioIDTerminalRuleCall_3_0_1 = (RuleCall)cPortfolioPortfolioCrossReference_3_0.eContents().get(1);
		private final Keyword cAmountKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAmountAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAmountFLOATParserRuleCall_5_0 = (RuleCall)cAmountAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Deposit:
		//    'deposit' '{'
		//        'portfolio' portfolio=[Portfolio]
		//        'amount' amount=FLOAT
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'deposit' '{'
		//    'portfolio' portfolio=[Portfolio]
		//    'amount' amount=FLOAT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'deposit'
		public Keyword getDepositKeyword_0() { return cDepositKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_2() { return cPortfolioKeyword_2; }
		
		//portfolio=[Portfolio]
		public Assignment getPortfolioAssignment_3() { return cPortfolioAssignment_3; }
		
		//[Portfolio]
		public CrossReference getPortfolioPortfolioCrossReference_3_0() { return cPortfolioPortfolioCrossReference_3_0; }
		
		//ID
		public RuleCall getPortfolioPortfolioIDTerminalRuleCall_3_0_1() { return cPortfolioPortfolioIDTerminalRuleCall_3_0_1; }
		
		//'amount'
		public Keyword getAmountKeyword_4() { return cAmountKeyword_4; }
		
		//amount=FLOAT
		public Assignment getAmountAssignment_5() { return cAmountAssignment_5; }
		
		//FLOAT
		public RuleCall getAmountFLOATParserRuleCall_5_0() { return cAmountFLOATParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class WithdrawalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Withdrawal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWithdrawalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPortfolioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortfolioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPortfolioPortfolioCrossReference_3_0 = (CrossReference)cPortfolioAssignment_3.eContents().get(0);
		private final RuleCall cPortfolioPortfolioIDTerminalRuleCall_3_0_1 = (RuleCall)cPortfolioPortfolioCrossReference_3_0.eContents().get(1);
		private final Keyword cAmountKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAmountAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAmountFLOATParserRuleCall_5_0 = (RuleCall)cAmountAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Withdrawal:
		//    'withdrawal' '{'
		//        'portfolio' portfolio=[Portfolio]
		//        'amount' amount=FLOAT
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'withdrawal' '{'
		//    'portfolio' portfolio=[Portfolio]
		//    'amount' amount=FLOAT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'withdrawal'
		public Keyword getWithdrawalKeyword_0() { return cWithdrawalKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_2() { return cPortfolioKeyword_2; }
		
		//portfolio=[Portfolio]
		public Assignment getPortfolioAssignment_3() { return cPortfolioAssignment_3; }
		
		//[Portfolio]
		public CrossReference getPortfolioPortfolioCrossReference_3_0() { return cPortfolioPortfolioCrossReference_3_0; }
		
		//ID
		public RuleCall getPortfolioPortfolioIDTerminalRuleCall_3_0_1() { return cPortfolioPortfolioIDTerminalRuleCall_3_0_1; }
		
		//'amount'
		public Keyword getAmountKeyword_4() { return cAmountKeyword_4; }
		
		//amount=FLOAT
		public Assignment getAmountAssignment_5() { return cAmountAssignment_5; }
		
		//FLOAT
		public RuleCall getAmountFLOATParserRuleCall_5_0() { return cAmountFLOATParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.View");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cViewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPortfolioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortfolioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPortfolioPortfolioCrossReference_3_0 = (CrossReference)cPortfolioAssignment_3.eContents().get(0);
		private final RuleCall cPortfolioPortfolioIDTerminalRuleCall_3_0_1 = (RuleCall)cPortfolioPortfolioCrossReference_3_0.eContents().get(1);
		private final Keyword cTimeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRangeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRangeINTTerminalRuleCall_5_0 = (RuleCall)cRangeAssignment_5.eContents().get(0);
		private final Assignment cUnitAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUnitTimeUnitEnumRuleCall_6_0 = (RuleCall)cUnitAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//View:
		//    'view' '{'
		//        'portfolio' portfolio=[Portfolio]
		//        'time' range=INT unit=TimeUnit
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'view' '{'
		//    'portfolio' portfolio=[Portfolio]
		//    'time' range=INT unit=TimeUnit
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'view'
		public Keyword getViewKeyword_0() { return cViewKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_2() { return cPortfolioKeyword_2; }
		
		//portfolio=[Portfolio]
		public Assignment getPortfolioAssignment_3() { return cPortfolioAssignment_3; }
		
		//[Portfolio]
		public CrossReference getPortfolioPortfolioCrossReference_3_0() { return cPortfolioPortfolioCrossReference_3_0; }
		
		//ID
		public RuleCall getPortfolioPortfolioIDTerminalRuleCall_3_0_1() { return cPortfolioPortfolioIDTerminalRuleCall_3_0_1; }
		
		//'time'
		public Keyword getTimeKeyword_4() { return cTimeKeyword_4; }
		
		//range=INT
		public Assignment getRangeAssignment_5() { return cRangeAssignment_5; }
		
		//INT
		public RuleCall getRangeINTTerminalRuleCall_5_0() { return cRangeINTTerminalRuleCall_5_0; }
		
		//unit=TimeUnit
		public Assignment getUnitAssignment_6() { return cUnitAssignment_6; }
		
		//TimeUnit
		public RuleCall getUnitTimeUnitEnumRuleCall_6_0() { return cUnitTimeUnitEnumRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class DeleteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.Delete");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDeleteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPortfolioKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPortfolioAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPortfolioPortfolioCrossReference_3_0 = (CrossReference)cPortfolioAssignment_3.eContents().get(0);
		private final RuleCall cPortfolioPortfolioIDTerminalRuleCall_3_0_1 = (RuleCall)cPortfolioPortfolioCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Delete:
		//    'delete' '{'
		//        'portfolio' portfolio=[Portfolio]
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'delete' '{'
		//    'portfolio' portfolio=[Portfolio]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'delete'
		public Keyword getDeleteKeyword_0() { return cDeleteKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'portfolio'
		public Keyword getPortfolioKeyword_2() { return cPortfolioKeyword_2; }
		
		//portfolio=[Portfolio]
		public Assignment getPortfolioAssignment_3() { return cPortfolioAssignment_3; }
		
		//[Portfolio]
		public CrossReference getPortfolioPortfolioCrossReference_3_0() { return cPortfolioPortfolioCrossReference_3_0; }
		
		//ID
		public RuleCall getPortfolioPortfolioIDTerminalRuleCall_3_0_1() { return cPortfolioPortfolioIDTerminalRuleCall_3_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FLOATElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.FLOAT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//FLOAT returns ecore::EFloat hidden():
		//    INT? "." INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//INT? "." INT
		public Group getGroup() { return cGroup; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	
	public class TimeUnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.TimeUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDayEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDayDayKeyword_0_0 = (Keyword)cDayEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMonthEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMonthMonthKeyword_1_0 = (Keyword)cMonthEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cYearEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cYearYearKeyword_2_0 = (Keyword)cYearEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TimeUnit:
		//    day | month | year
		//;
		public EnumRule getRule() { return rule; }
		
		//day | month | year
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//day
		public EnumLiteralDeclaration getDayEnumLiteralDeclaration_0() { return cDayEnumLiteralDeclaration_0; }
		
		public Keyword getDayDayKeyword_0_0() { return cDayDayKeyword_0_0; }
		
		//month
		public EnumLiteralDeclaration getMonthEnumLiteralDeclaration_1() { return cMonthEnumLiteralDeclaration_1; }
		
		public Keyword getMonthMonthKeyword_1_0() { return cMonthMonthKeyword_1_0; }
		
		//year
		public EnumLiteralDeclaration getYearEnumLiteralDeclaration_2() { return cYearEnumLiteralDeclaration_2; }
		
		public Keyword getYearYearKeyword_2_0() { return cYearYearKeyword_2_0; }
	}
	public class OptionTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.mydsl.Fin.OptionType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCallEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCallCallKeyword_0_0 = (Keyword)cCallEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPutEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPutPutKeyword_1_0 = (Keyword)cPutEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum OptionType:
		//    Call | Put
		//;
		public EnumRule getRule() { return rule; }
		
		//Call | Put
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Call
		public EnumLiteralDeclaration getCallEnumLiteralDeclaration_0() { return cCallEnumLiteralDeclaration_0; }
		
		public Keyword getCallCallKeyword_0_0() { return cCallCallKeyword_0_0; }
		
		//Put
		public EnumLiteralDeclaration getPutEnumLiteralDeclaration_1() { return cPutEnumLiteralDeclaration_1; }
		
		public Keyword getPutPutKeyword_1_0() { return cPutPutKeyword_1_0; }
	}
	
	private final ModelElements pModel;
	private final ElementElements pElement;
	private final AssetElements pAsset;
	private final TransactionElements pTransaction;
	private final ActionElements pAction;
	private final PortfolioElements pPortfolio;
	private final BondElements pBond;
	private final OptionElements pOption;
	private final CashElements pCash;
	private final BuyElements pBuy;
	private final SellElements pSell;
	private final DepositElements pDeposit;
	private final WithdrawalElements pWithdrawal;
	private final ViewElements pView;
	private final DeleteElements pDelete;
	private final TimeUnitElements eTimeUnit;
	private final OptionTypeElements eOptionType;
	private final FLOATElements pFLOAT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public FinGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pElement = new ElementElements();
		this.pAsset = new AssetElements();
		this.pTransaction = new TransactionElements();
		this.pAction = new ActionElements();
		this.pPortfolio = new PortfolioElements();
		this.pBond = new BondElements();
		this.pOption = new OptionElements();
		this.pCash = new CashElements();
		this.pBuy = new BuyElements();
		this.pSell = new SellElements();
		this.pDeposit = new DepositElements();
		this.pWithdrawal = new WithdrawalElements();
		this.pView = new ViewElements();
		this.pDelete = new DeleteElements();
		this.eTimeUnit = new TimeUnitElements();
		this.eOptionType = new OptionTypeElements();
		this.pFLOAT = new FLOATElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.mydsl.Fin".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    (element+=Element)*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Element:
	//    Portfolio | Transaction | Action
	//;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Asset:
	//    Bond | Option | Cash
	//;
	public AssetElements getAssetAccess() {
		return pAsset;
	}
	
	public ParserRule getAssetRule() {
		return getAssetAccess().getRule();
	}
	
	//Transaction:
	//    Buy | Sell | Deposit | Withdrawal
	//;
	public TransactionElements getTransactionAccess() {
		return pTransaction;
	}
	
	public ParserRule getTransactionRule() {
		return getTransactionAccess().getRule();
	}
	
	//Action:
	//    View | Delete
	//;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//Portfolio:
	//    'portfolio' name=ID '{'
	//        (asset+=Asset)+
	//    '}'
	//;
	public PortfolioElements getPortfolioAccess() {
		return pPortfolio;
	}
	
	public ParserRule getPortfolioRule() {
		return getPortfolioAccess().getRule();
	}
	
	//Bond:
	//    'bond' name=ID '{'
	//        'faceValue' faceValue=FLOAT
	//        'couponRate' couponRate=FLOAT
	//        'maturity' maturity=INT
	//        'yieldRate' yieldRate=FLOAT
	//    '}'
	//;
	public BondElements getBondAccess() {
		return pBond;
	}
	
	public ParserRule getBondRule() {
		return getBondAccess().getRule();
	}
	
	//Option:
	//    'option' name=ID '{'
	//        'type' type=OptionType
	//        'underlyingPrice' underlyingPrice=FLOAT
	//        'strikePrice' strikePrice=FLOAT
	//        'timeToExpiration' timeToExpiration=FLOAT
	//        'riskFreeRate' riskFreeRate=FLOAT
	//        'volatility' volatility=FLOAT
	//        'dividendYield' dividendYield=FLOAT
	//    '}'
	//;
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//Cash:
	//    'cash' '{'
	//        'amount' amount=FLOAT
	//    '}'
	//;
	public CashElements getCashAccess() {
		return pCash;
	}
	
	public ParserRule getCashRule() {
		return getCashAccess().getRule();
	}
	
	//Buy:
	//    'buy' '{'
	//        'portfolio' portfolio=[Portfolio]
	//        (bond+=Bond | option+=Option)+
	//    '}'
	//;
	public BuyElements getBuyAccess() {
		return pBuy;
	}
	
	public ParserRule getBuyRule() {
		return getBuyAccess().getRule();
	}
	
	//Sell:
	//    'sell' '{'
	//        'portfolio' portfolio=[Portfolio]
	//        ('bond' bond=[Bond])*
	//        ('option' option=[Option])*
	//    '}'
	//;
	public SellElements getSellAccess() {
		return pSell;
	}
	
	public ParserRule getSellRule() {
		return getSellAccess().getRule();
	}
	
	//Deposit:
	//    'deposit' '{'
	//        'portfolio' portfolio=[Portfolio]
	//        'amount' amount=FLOAT
	//    '}'
	//;
	public DepositElements getDepositAccess() {
		return pDeposit;
	}
	
	public ParserRule getDepositRule() {
		return getDepositAccess().getRule();
	}
	
	//Withdrawal:
	//    'withdrawal' '{'
	//        'portfolio' portfolio=[Portfolio]
	//        'amount' amount=FLOAT
	//    '}'
	//;
	public WithdrawalElements getWithdrawalAccess() {
		return pWithdrawal;
	}
	
	public ParserRule getWithdrawalRule() {
		return getWithdrawalAccess().getRule();
	}
	
	//View:
	//    'view' '{'
	//        'portfolio' portfolio=[Portfolio]
	//        'time' range=INT unit=TimeUnit
	//    '}'
	//;
	public ViewElements getViewAccess() {
		return pView;
	}
	
	public ParserRule getViewRule() {
		return getViewAccess().getRule();
	}
	
	//Delete:
	//    'delete' '{'
	//        'portfolio' portfolio=[Portfolio]
	//    '}'
	//;
	public DeleteElements getDeleteAccess() {
		return pDelete;
	}
	
	public ParserRule getDeleteRule() {
		return getDeleteAccess().getRule();
	}
	
	//enum TimeUnit:
	//    day | month | year
	//;
	public TimeUnitElements getTimeUnitAccess() {
		return eTimeUnit;
	}
	
	public EnumRule getTimeUnitRule() {
		return getTimeUnitAccess().getRule();
	}
	
	//enum OptionType:
	//    Call | Put
	//;
	public OptionTypeElements getOptionTypeAccess() {
		return eOptionType;
	}
	
	public EnumRule getOptionTypeRule() {
		return getOptionTypeAccess().getRule();
	}
	
	//FLOAT returns ecore::EFloat hidden():
	//    INT? "." INT
	//;
	public FLOATElements getFLOATAccess() {
		return pFLOAT;
	}
	
	public ParserRule getFLOATRule() {
		return getFLOATAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
