/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.xtext.mydsl.fin.Buy;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FinScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_Buy_var(final Buy context, final EReference ref) {
    return null;
  }
}
