/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.scoping;

import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.xtext.mydsl.fin.Bond;
import org.xtext.mydsl.fin.Option;
import org.xtext.mydsl.fin.Sell;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FinScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_Sell_bond(final Sell sell, final EReference reference) {
    final EObject root = EcoreUtil2.getRootContainer(sell);
    final List<Bond> allBonds = EcoreUtil2.<Bond>getAllContentsOfType(root, Bond.class);
    return Scopes.scopeFor(allBonds);
  }

  public IScope scope_Sell_option(final Sell sell, final EReference reference) {
    final EObject root = EcoreUtil2.getRootContainer(sell);
    final List<Option> allOptions = EcoreUtil2.<Option>getAllContentsOfType(root, Option.class);
    return Scopes.scopeFor(allOptions);
  }
}
