/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class FinUiModule extends AbstractFinUiModule {
}
