/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FinUiModule extends AbstractFinUiModule {

	public FinUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
