/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FinStandaloneSetup extends FinStandaloneSetupGenerated {

	public static void doSetup() {
		new FinStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
