/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FinRuntimeModule extends AbstractFinRuntimeModule {
}
