/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mydsl.fin.FinPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends Element
{
} // Action
