/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asset</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mydsl.fin.FinPackage#getAsset()
 * @model
 * @generated
 */
public interface Asset extends EObject
{
} // Asset
