/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bond</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Bond#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Bond#getFaceValue <em>Face Value</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Bond#getCouponRate <em>Coupon Rate</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Bond#getMaturity <em>Maturity</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Bond#getYieldRate <em>Yield Rate</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getBond()
 * @model
 * @generated
 */
public interface Bond extends Asset
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mydsl.fin.FinPackage#getBond_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Bond#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Face Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Face Value</em>' attribute.
   * @see #setFaceValue(float)
   * @see org.xtext.mydsl.fin.FinPackage#getBond_FaceValue()
   * @model
   * @generated
   */
  float getFaceValue();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Bond#getFaceValue <em>Face Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Face Value</em>' attribute.
   * @see #getFaceValue()
   * @generated
   */
  void setFaceValue(float value);

  /**
   * Returns the value of the '<em><b>Coupon Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coupon Rate</em>' attribute.
   * @see #setCouponRate(float)
   * @see org.xtext.mydsl.fin.FinPackage#getBond_CouponRate()
   * @model
   * @generated
   */
  float getCouponRate();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Bond#getCouponRate <em>Coupon Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coupon Rate</em>' attribute.
   * @see #getCouponRate()
   * @generated
   */
  void setCouponRate(float value);

  /**
   * Returns the value of the '<em><b>Maturity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maturity</em>' attribute.
   * @see #setMaturity(int)
   * @see org.xtext.mydsl.fin.FinPackage#getBond_Maturity()
   * @model
   * @generated
   */
  int getMaturity();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Bond#getMaturity <em>Maturity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maturity</em>' attribute.
   * @see #getMaturity()
   * @generated
   */
  void setMaturity(int value);

  /**
   * Returns the value of the '<em><b>Yield Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Yield Rate</em>' attribute.
   * @see #setYieldRate(float)
   * @see org.xtext.mydsl.fin.FinPackage#getBond_YieldRate()
   * @model
   * @generated
   */
  float getYieldRate();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Bond#getYieldRate <em>Yield Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Yield Rate</em>' attribute.
   * @see #getYieldRate()
   * @generated
   */
  void setYieldRate(float value);

} // Bond
