/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buy</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Buy#getBond <em>Bond</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Buy#getOption <em>Option</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getBuy()
 * @model
 * @generated
 */
public interface Buy extends Transaction
{
  /**
   * Returns the value of the '<em><b>Bond</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mydsl.fin.Bond}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bond</em>' containment reference list.
   * @see org.xtext.mydsl.fin.FinPackage#getBuy_Bond()
   * @model containment="true"
   * @generated
   */
  EList<Bond> getBond();

  /**
   * Returns the value of the '<em><b>Option</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mydsl.fin.Option}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Option</em>' containment reference list.
   * @see org.xtext.mydsl.fin.FinPackage#getBuy_Option()
   * @model containment="true"
   * @generated
   */
  EList<Option> getOption();

} // Buy
