/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cash</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Cash#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getCash()
 * @model
 * @generated
 */
public interface Cash extends Asset
{
  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(float)
   * @see org.xtext.mydsl.fin.FinPackage#getCash_Amount()
   * @model
   * @generated
   */
  float getAmount();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Cash#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(float value);

} // Cash
