/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Display</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Display#getDisplayType <em>Display Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getDisplay()
 * @model
 * @generated
 */
public interface Display extends Action
{
  /**
   * Returns the value of the '<em><b>Display Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Display Type</em>' attribute.
   * @see #setDisplayType(String)
   * @see org.xtext.mydsl.fin.FinPackage#getDisplay_DisplayType()
   * @model
   * @generated
   */
  String getDisplayType();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Display#getDisplayType <em>Display Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Display Type</em>' attribute.
   * @see #getDisplayType()
   * @generated
   */
  void setDisplayType(String value);

} // Display
