/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mydsl.fin.FinFactory
 * @model kind="package"
 * @generated
 */
public interface FinPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fin";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mydsl/Fin";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fin";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FinPackage eINSTANCE = org.xtext.mydsl.fin.impl.FinPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.ModelImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.ElementImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.AssetImpl <em>Asset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.AssetImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getAsset()
   * @generated
   */
  int ASSET = 2;

  /**
   * The number of structural features of the '<em>Asset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSET_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.TransactionImpl <em>Transaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.TransactionImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getTransaction()
   * @generated
   */
  int TRANSACTION = 3;

  /**
   * The number of structural features of the '<em>Transaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.ActionImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getAction()
   * @generated
   */
  int ACTION = 4;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.PortfolioImpl <em>Portfolio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.PortfolioImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getPortfolio()
   * @generated
   */
  int PORTFOLIO = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTFOLIO__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Asset</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTFOLIO__ASSET = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Portfolio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTFOLIO_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.BondImpl <em>Bond</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.BondImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getBond()
   * @generated
   */
  int BOND = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOND__NAME = ASSET_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Face Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOND__FACE_VALUE = ASSET_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Coupon Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOND__COUPON_RATE = ASSET_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Maturity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOND__MATURITY = ASSET_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Yield Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOND__YIELD_RATE = ASSET_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Bond</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOND_FEATURE_COUNT = ASSET_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.OptionImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getOption()
   * @generated
   */
  int OPTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__NAME = ASSET_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__TYPE = ASSET_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Underlying Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__UNDERLYING_PRICE = ASSET_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Strike Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__STRIKE_PRICE = ASSET_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Time To Expiration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__TIME_TO_EXPIRATION = ASSET_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Risk Free Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__RISK_FREE_RATE = ASSET_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Volatility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__VOLATILITY = ASSET_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Dividend Yield</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION__DIVIDEND_YIELD = ASSET_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = ASSET_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.CashImpl <em>Cash</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.CashImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getCash()
   * @generated
   */
  int CASH = 8;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASH__AMOUNT = ASSET_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cash</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASH_FEATURE_COUNT = ASSET_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.BuyImpl <em>Buy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.BuyImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getBuy()
   * @generated
   */
  int BUY = 9;

  /**
   * The feature id for the '<em><b>Bond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY__BOND = TRANSACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY__OPTION = TRANSACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Buy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY_FEATURE_COUNT = TRANSACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.SellImpl <em>Sell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.SellImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getSell()
   * @generated
   */
  int SELL = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL__NAME = TRANSACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL__AMOUNT = TRANSACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL_FEATURE_COUNT = TRANSACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.DepositImpl <em>Deposit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.DepositImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getDeposit()
   * @generated
   */
  int DEPOSIT = 11;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOSIT__AMOUNT = TRANSACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Deposit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPOSIT_FEATURE_COUNT = TRANSACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.WithdrawalImpl <em>Withdrawal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.WithdrawalImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getWithdrawal()
   * @generated
   */
  int WITHDRAWAL = 12;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITHDRAWAL__AMOUNT = TRANSACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Withdrawal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WITHDRAWAL_FEATURE_COUNT = TRANSACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.impl.ViewImpl <em>View</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.impl.ViewImpl
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getView()
   * @generated
   */
  int VIEW = 13;

  /**
   * The feature id for the '<em><b>View Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIEW__VIEW_TYPE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIEW__TIME = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>View</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIEW_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mydsl.fin.OptionType <em>Option Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mydsl.fin.OptionType
   * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getOptionType()
   * @generated
   */
  int OPTION_TYPE = 14;


  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.mydsl.fin.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mydsl.fin.Model#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see org.xtext.mydsl.fin.Model#getElement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Element();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.mydsl.fin.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Asset <em>Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asset</em>'.
   * @see org.xtext.mydsl.fin.Asset
   * @generated
   */
  EClass getAsset();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Transaction <em>Transaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transaction</em>'.
   * @see org.xtext.mydsl.fin.Transaction
   * @generated
   */
  EClass getTransaction();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.mydsl.fin.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Portfolio <em>Portfolio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Portfolio</em>'.
   * @see org.xtext.mydsl.fin.Portfolio
   * @generated
   */
  EClass getPortfolio();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Portfolio#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mydsl.fin.Portfolio#getName()
   * @see #getPortfolio()
   * @generated
   */
  EAttribute getPortfolio_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mydsl.fin.Portfolio#getAsset <em>Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Asset</em>'.
   * @see org.xtext.mydsl.fin.Portfolio#getAsset()
   * @see #getPortfolio()
   * @generated
   */
  EReference getPortfolio_Asset();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Bond <em>Bond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bond</em>'.
   * @see org.xtext.mydsl.fin.Bond
   * @generated
   */
  EClass getBond();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Bond#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mydsl.fin.Bond#getName()
   * @see #getBond()
   * @generated
   */
  EAttribute getBond_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Bond#getFaceValue <em>Face Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Face Value</em>'.
   * @see org.xtext.mydsl.fin.Bond#getFaceValue()
   * @see #getBond()
   * @generated
   */
  EAttribute getBond_FaceValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Bond#getCouponRate <em>Coupon Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Coupon Rate</em>'.
   * @see org.xtext.mydsl.fin.Bond#getCouponRate()
   * @see #getBond()
   * @generated
   */
  EAttribute getBond_CouponRate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Bond#getMaturity <em>Maturity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Maturity</em>'.
   * @see org.xtext.mydsl.fin.Bond#getMaturity()
   * @see #getBond()
   * @generated
   */
  EAttribute getBond_Maturity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Bond#getYieldRate <em>Yield Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Yield Rate</em>'.
   * @see org.xtext.mydsl.fin.Bond#getYieldRate()
   * @see #getBond()
   * @generated
   */
  EAttribute getBond_YieldRate();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see org.xtext.mydsl.fin.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mydsl.fin.Option#getName()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.mydsl.fin.Option#getType()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getUnderlyingPrice <em>Underlying Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Underlying Price</em>'.
   * @see org.xtext.mydsl.fin.Option#getUnderlyingPrice()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_UnderlyingPrice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getStrikePrice <em>Strike Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Strike Price</em>'.
   * @see org.xtext.mydsl.fin.Option#getStrikePrice()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_StrikePrice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getTimeToExpiration <em>Time To Expiration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time To Expiration</em>'.
   * @see org.xtext.mydsl.fin.Option#getTimeToExpiration()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_TimeToExpiration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getRiskFreeRate <em>Risk Free Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Risk Free Rate</em>'.
   * @see org.xtext.mydsl.fin.Option#getRiskFreeRate()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_RiskFreeRate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getVolatility <em>Volatility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Volatility</em>'.
   * @see org.xtext.mydsl.fin.Option#getVolatility()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_Volatility();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Option#getDividendYield <em>Dividend Yield</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dividend Yield</em>'.
   * @see org.xtext.mydsl.fin.Option#getDividendYield()
   * @see #getOption()
   * @generated
   */
  EAttribute getOption_DividendYield();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Cash <em>Cash</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cash</em>'.
   * @see org.xtext.mydsl.fin.Cash
   * @generated
   */
  EClass getCash();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Cash#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.mydsl.fin.Cash#getAmount()
   * @see #getCash()
   * @generated
   */
  EAttribute getCash_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Buy <em>Buy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Buy</em>'.
   * @see org.xtext.mydsl.fin.Buy
   * @generated
   */
  EClass getBuy();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.fin.Buy#getBond <em>Bond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bond</em>'.
   * @see org.xtext.mydsl.fin.Buy#getBond()
   * @see #getBuy()
   * @generated
   */
  EReference getBuy_Bond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mydsl.fin.Buy#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Option</em>'.
   * @see org.xtext.mydsl.fin.Buy#getOption()
   * @see #getBuy()
   * @generated
   */
  EReference getBuy_Option();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Sell <em>Sell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sell</em>'.
   * @see org.xtext.mydsl.fin.Sell
   * @generated
   */
  EClass getSell();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Sell#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.mydsl.fin.Sell#getName()
   * @see #getSell()
   * @generated
   */
  EAttribute getSell_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Sell#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.mydsl.fin.Sell#getAmount()
   * @see #getSell()
   * @generated
   */
  EAttribute getSell_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Deposit <em>Deposit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deposit</em>'.
   * @see org.xtext.mydsl.fin.Deposit
   * @generated
   */
  EClass getDeposit();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Deposit#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.mydsl.fin.Deposit#getAmount()
   * @see #getDeposit()
   * @generated
   */
  EAttribute getDeposit_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.Withdrawal <em>Withdrawal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Withdrawal</em>'.
   * @see org.xtext.mydsl.fin.Withdrawal
   * @generated
   */
  EClass getWithdrawal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.Withdrawal#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see org.xtext.mydsl.fin.Withdrawal#getAmount()
   * @see #getWithdrawal()
   * @generated
   */
  EAttribute getWithdrawal_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.mydsl.fin.View <em>View</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>View</em>'.
   * @see org.xtext.mydsl.fin.View
   * @generated
   */
  EClass getView();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.View#getViewType <em>View Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>View Type</em>'.
   * @see org.xtext.mydsl.fin.View#getViewType()
   * @see #getView()
   * @generated
   */
  EAttribute getView_ViewType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mydsl.fin.View#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.mydsl.fin.View#getTime()
   * @see #getView()
   * @generated
   */
  EAttribute getView_Time();

  /**
   * Returns the meta object for enum '{@link org.xtext.mydsl.fin.OptionType <em>Option Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Option Type</em>'.
   * @see org.xtext.mydsl.fin.OptionType
   * @generated
   */
  EEnum getOptionType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FinFactory getFinFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.ModelImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENT = eINSTANCE.getModel_Element();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.ElementImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.AssetImpl <em>Asset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.AssetImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getAsset()
     * @generated
     */
    EClass ASSET = eINSTANCE.getAsset();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.TransactionImpl <em>Transaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.TransactionImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getTransaction()
     * @generated
     */
    EClass TRANSACTION = eINSTANCE.getTransaction();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.ActionImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.PortfolioImpl <em>Portfolio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.PortfolioImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getPortfolio()
     * @generated
     */
    EClass PORTFOLIO = eINSTANCE.getPortfolio();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORTFOLIO__NAME = eINSTANCE.getPortfolio_Name();

    /**
     * The meta object literal for the '<em><b>Asset</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORTFOLIO__ASSET = eINSTANCE.getPortfolio_Asset();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.BondImpl <em>Bond</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.BondImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getBond()
     * @generated
     */
    EClass BOND = eINSTANCE.getBond();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOND__NAME = eINSTANCE.getBond_Name();

    /**
     * The meta object literal for the '<em><b>Face Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOND__FACE_VALUE = eINSTANCE.getBond_FaceValue();

    /**
     * The meta object literal for the '<em><b>Coupon Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOND__COUPON_RATE = eINSTANCE.getBond_CouponRate();

    /**
     * The meta object literal for the '<em><b>Maturity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOND__MATURITY = eINSTANCE.getBond_Maturity();

    /**
     * The meta object literal for the '<em><b>Yield Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOND__YIELD_RATE = eINSTANCE.getBond_YieldRate();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.OptionImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__NAME = eINSTANCE.getOption_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__TYPE = eINSTANCE.getOption_Type();

    /**
     * The meta object literal for the '<em><b>Underlying Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__UNDERLYING_PRICE = eINSTANCE.getOption_UnderlyingPrice();

    /**
     * The meta object literal for the '<em><b>Strike Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__STRIKE_PRICE = eINSTANCE.getOption_StrikePrice();

    /**
     * The meta object literal for the '<em><b>Time To Expiration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__TIME_TO_EXPIRATION = eINSTANCE.getOption_TimeToExpiration();

    /**
     * The meta object literal for the '<em><b>Risk Free Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__RISK_FREE_RATE = eINSTANCE.getOption_RiskFreeRate();

    /**
     * The meta object literal for the '<em><b>Volatility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__VOLATILITY = eINSTANCE.getOption_Volatility();

    /**
     * The meta object literal for the '<em><b>Dividend Yield</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPTION__DIVIDEND_YIELD = eINSTANCE.getOption_DividendYield();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.CashImpl <em>Cash</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.CashImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getCash()
     * @generated
     */
    EClass CASH = eINSTANCE.getCash();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CASH__AMOUNT = eINSTANCE.getCash_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.BuyImpl <em>Buy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.BuyImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getBuy()
     * @generated
     */
    EClass BUY = eINSTANCE.getBuy();

    /**
     * The meta object literal for the '<em><b>Bond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUY__BOND = eINSTANCE.getBuy_Bond();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUY__OPTION = eINSTANCE.getBuy_Option();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.SellImpl <em>Sell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.SellImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getSell()
     * @generated
     */
    EClass SELL = eINSTANCE.getSell();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELL__NAME = eINSTANCE.getSell_Name();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELL__AMOUNT = eINSTANCE.getSell_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.DepositImpl <em>Deposit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.DepositImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getDeposit()
     * @generated
     */
    EClass DEPOSIT = eINSTANCE.getDeposit();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPOSIT__AMOUNT = eINSTANCE.getDeposit_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.WithdrawalImpl <em>Withdrawal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.WithdrawalImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getWithdrawal()
     * @generated
     */
    EClass WITHDRAWAL = eINSTANCE.getWithdrawal();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WITHDRAWAL__AMOUNT = eINSTANCE.getWithdrawal_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.impl.ViewImpl <em>View</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.impl.ViewImpl
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getView()
     * @generated
     */
    EClass VIEW = eINSTANCE.getView();

    /**
     * The meta object literal for the '<em><b>View Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIEW__VIEW_TYPE = eINSTANCE.getView_ViewType();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIEW__TIME = eINSTANCE.getView_Time();

    /**
     * The meta object literal for the '{@link org.xtext.mydsl.fin.OptionType <em>Option Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mydsl.fin.OptionType
     * @see org.xtext.mydsl.fin.impl.FinPackageImpl#getOptionType()
     * @generated
     */
    EEnum OPTION_TYPE = eINSTANCE.getOptionType();

  }

} //FinPackage
