/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Model#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mydsl.fin.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference list.
   * @see org.xtext.mydsl.fin.FinPackage#getModel_Element()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElement();

} // Model
