/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Option#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getUnderlyingPrice <em>Underlying Price</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getStrikePrice <em>Strike Price</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getTimeToExpiration <em>Time To Expiration</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getRiskFreeRate <em>Risk Free Rate</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getVolatility <em>Volatility</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.Option#getDividendYield <em>Dividend Yield</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getOption()
 * @model
 * @generated
 */
public interface Option extends Asset
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mydsl.fin.OptionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.mydsl.fin.OptionType
   * @see #setType(OptionType)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_Type()
   * @model
   * @generated
   */
  OptionType getType();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.mydsl.fin.OptionType
   * @see #getType()
   * @generated
   */
  void setType(OptionType value);

  /**
   * Returns the value of the '<em><b>Underlying Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Underlying Price</em>' attribute.
   * @see #setUnderlyingPrice(float)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_UnderlyingPrice()
   * @model
   * @generated
   */
  float getUnderlyingPrice();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getUnderlyingPrice <em>Underlying Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Underlying Price</em>' attribute.
   * @see #getUnderlyingPrice()
   * @generated
   */
  void setUnderlyingPrice(float value);

  /**
   * Returns the value of the '<em><b>Strike Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strike Price</em>' attribute.
   * @see #setStrikePrice(float)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_StrikePrice()
   * @model
   * @generated
   */
  float getStrikePrice();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getStrikePrice <em>Strike Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strike Price</em>' attribute.
   * @see #getStrikePrice()
   * @generated
   */
  void setStrikePrice(float value);

  /**
   * Returns the value of the '<em><b>Time To Expiration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time To Expiration</em>' attribute.
   * @see #setTimeToExpiration(float)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_TimeToExpiration()
   * @model
   * @generated
   */
  float getTimeToExpiration();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getTimeToExpiration <em>Time To Expiration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time To Expiration</em>' attribute.
   * @see #getTimeToExpiration()
   * @generated
   */
  void setTimeToExpiration(float value);

  /**
   * Returns the value of the '<em><b>Risk Free Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Risk Free Rate</em>' attribute.
   * @see #setRiskFreeRate(float)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_RiskFreeRate()
   * @model
   * @generated
   */
  float getRiskFreeRate();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getRiskFreeRate <em>Risk Free Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Risk Free Rate</em>' attribute.
   * @see #getRiskFreeRate()
   * @generated
   */
  void setRiskFreeRate(float value);

  /**
   * Returns the value of the '<em><b>Volatility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Volatility</em>' attribute.
   * @see #setVolatility(float)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_Volatility()
   * @model
   * @generated
   */
  float getVolatility();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getVolatility <em>Volatility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Volatility</em>' attribute.
   * @see #getVolatility()
   * @generated
   */
  void setVolatility(float value);

  /**
   * Returns the value of the '<em><b>Dividend Yield</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dividend Yield</em>' attribute.
   * @see #setDividendYield(float)
   * @see org.xtext.mydsl.fin.FinPackage#getOption_DividendYield()
   * @model
   * @generated
   */
  float getDividendYield();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Option#getDividendYield <em>Dividend Yield</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dividend Yield</em>' attribute.
   * @see #getDividendYield()
   * @generated
   */
  void setDividendYield(float value);

} // Option
