/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Portfolio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Portfolio#getAsset <em>Asset</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getPortfolio()
 * @model
 * @generated
 */
public interface Portfolio extends Element
{
  /**
   * Returns the value of the '<em><b>Asset</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mydsl.fin.Asset}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asset</em>' containment reference list.
   * @see org.xtext.mydsl.fin.FinPackage#getPortfolio_Asset()
   * @model containment="true"
   * @generated
   */
  EList<Asset> getAsset();

} // Portfolio
