/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.Transaction#getPortfolio <em>Portfolio</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getTransaction()
 * @model
 * @generated
 */
public interface Transaction extends Element
{
  /**
   * Returns the value of the '<em><b>Portfolio</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Portfolio</em>' reference.
   * @see #setPortfolio(Portfolio)
   * @see org.xtext.mydsl.fin.FinPackage#getTransaction_Portfolio()
   * @model
   * @generated
   */
  Portfolio getPortfolio();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.Transaction#getPortfolio <em>Portfolio</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Portfolio</em>' reference.
   * @see #getPortfolio()
   * @generated
   */
  void setPortfolio(Portfolio value);

} // Transaction
