/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transaction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mydsl.fin.FinPackage#getTransaction()
 * @model
 * @generated
 */
public interface Transaction extends Element
{
} // Transaction
