/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>View</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.View#getTargetType <em>Target Type</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.View#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getView()
 * @model
 * @generated
 */
public interface View extends Action
{
  /**
   * Returns the value of the '<em><b>Target Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mydsl.fin.ViewType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Type</em>' attribute.
   * @see org.xtext.mydsl.fin.ViewType
   * @see #setTargetType(ViewType)
   * @see org.xtext.mydsl.fin.FinPackage#getView_TargetType()
   * @model
   * @generated
   */
  ViewType getTargetType();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.View#getTargetType <em>Target Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Type</em>' attribute.
   * @see org.xtext.mydsl.fin.ViewType
   * @see #getTargetType()
   * @generated
   */
  void setTargetType(ViewType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mydsl.fin.FinPackage#getView_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.View#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // View
