/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>View Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.mydsl.fin.FinPackage#getViewType()
 * @model
 * @generated
 */
public enum ViewType implements Enumerator
{
  /**
   * The '<em><b>Portfolio</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PORTFOLIO_VALUE
   * @generated
   * @ordered
   */
  PORTFOLIO(0, "Portfolio", "Portfolio"),

  /**
   * The '<em><b>Bond</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOND_VALUE
   * @generated
   * @ordered
   */
  BOND(1, "Bond", "Bond"),

  /**
   * The '<em><b>Option</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OPTION_VALUE
   * @generated
   * @ordered
   */
  OPTION(2, "Option", "Option"),

  /**
   * The '<em><b>Cash</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CASH_VALUE
   * @generated
   * @ordered
   */
  CASH(3, "Cash", "Cash");

  /**
   * The '<em><b>Portfolio</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PORTFOLIO
   * @model name="Portfolio"
   * @generated
   * @ordered
   */
  public static final int PORTFOLIO_VALUE = 0;

  /**
   * The '<em><b>Bond</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BOND
   * @model name="Bond"
   * @generated
   * @ordered
   */
  public static final int BOND_VALUE = 1;

  /**
   * The '<em><b>Option</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OPTION
   * @model name="Option"
   * @generated
   * @ordered
   */
  public static final int OPTION_VALUE = 2;

  /**
   * The '<em><b>Cash</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CASH
   * @model name="Cash"
   * @generated
   * @ordered
   */
  public static final int CASH_VALUE = 3;

  /**
   * An array of all the '<em><b>View Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ViewType[] VALUES_ARRAY =
    new ViewType[]
    {
      PORTFOLIO,
      BOND,
      OPTION,
      CASH,
    };

  /**
   * A public read-only list of all the '<em><b>View Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ViewType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>View Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ViewType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ViewType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>View Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ViewType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ViewType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>View Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ViewType get(int value)
  {
    switch (value)
    {
      case PORTFOLIO_VALUE: return PORTFOLIO;
      case BOND_VALUE: return BOND;
      case OPTION_VALUE: return OPTION;
      case CASH_VALUE: return CASH;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ViewType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ViewType
