/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>View</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.View#getViewType <em>View Type</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.View#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getView()
 * @model
 * @generated
 */
public interface View extends Action
{
  /**
   * Returns the value of the '<em><b>View Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>View Type</em>' attribute.
   * @see #setViewType(String)
   * @see org.xtext.mydsl.fin.FinPackage#getView_ViewType()
   * @model
   * @generated
   */
  String getViewType();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.View#getViewType <em>View Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>View Type</em>' attribute.
   * @see #getViewType()
   * @generated
   */
  void setViewType(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see org.xtext.mydsl.fin.FinPackage#getView_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.View#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

} // View
