/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.fin;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>View</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mydsl.fin.View#getRange <em>Range</em>}</li>
 *   <li>{@link org.xtext.mydsl.fin.View#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.mydsl.fin.FinPackage#getView()
 * @model
 * @generated
 */
public interface View extends Action
{
  /**
   * Returns the value of the '<em><b>Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' attribute.
   * @see #setRange(int)
   * @see org.xtext.mydsl.fin.FinPackage#getView_Range()
   * @model
   * @generated
   */
  int getRange();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.View#getRange <em>Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' attribute.
   * @see #getRange()
   * @generated
   */
  void setRange(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.mydsl.fin.TimeUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see org.xtext.mydsl.fin.TimeUnit
   * @see #setUnit(TimeUnit)
   * @see org.xtext.mydsl.fin.FinPackage#getView_Unit()
   * @model
   * @generated
   */
  TimeUnit getUnit();

  /**
   * Sets the value of the '{@link org.xtext.mydsl.fin.View#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see org.xtext.mydsl.fin.TimeUnit
   * @see #getUnit()
   * @generated
   */
  void setUnit(TimeUnit value);

} // View
