/**
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class FinIdeModule extends AbstractFinIdeModule {
}
