/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.financedsml.ui.internal.FinancedsmlActivator;

public class FinUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FinancedsmlActivator.getInstance().getInjector("org.xtext.mydsl.Fin");
	}

}
