/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mydsl.parser.antlr.internal.InternalFinParser;
import org.xtext.mydsl.services.FinGrammarAccess;

public class FinParser extends AbstractAntlrParser {

	@Inject
	private FinGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFinParser createParser(XtextTokenStream stream) {
		return new InternalFinParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public FinGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FinGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
