/*
 * generated by Xtext 2.33.0
 */
package org.xtext.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.financedsml.ui.internal.FinancedsmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FinExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FinancedsmlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FinancedsmlActivator activator = FinancedsmlActivator.getInstance();
		return activator != null ? activator.getInjector(FinancedsmlActivator.ORG_XTEXT_MYDSL_FIN) : null;
	}

}
